-- 1) ABS0000 (โอนจริง) moves onto the multi-file model (0012/0013).
-- Real exports are capped at 5,000 rows, so a week routinely arrives as
-- several disjoint ABS0000 files (e.g. WK32: 5,000 + 5,000 + 148 rows). As a
-- single-file slot, uploading the second file deleted the first file's rows,
-- silently understating โอนจริง. All files in the category now combine;
-- re-uploading a same-named file replaces just that file.

alter table upload_files drop constraint upload_files_file_type_check;
alter table upload_files add constraint upload_files_file_type_check
  check (file_type in (
    'supply_daily_bsd010', 'pricing_daily', 'bidding_tc05', 'plan_daily_bdr130', 'actual_abs0000'
  ));

alter table actual_rows add column upload_file_id uuid references upload_files (id) on delete cascade;
create index actual_rows_upload_file_idx on actual_rows (upload_file_id);

-- Backfill: every week's existing single-file ABS0000 upload becomes an
-- upload_files row and its live actual_rows get tagged to it, so data that's
-- already uploaded stays visible (and deletable) in the new per-file list.
do $$
declare
  u record;
  new_id uuid;
begin
  for u in select * from uploads where file_type = 'actual_abs0000' and status = 'validated' loop
    insert into upload_files (week_id, file_type, original_filename, storage_path, status, row_count, skipped_count, error_report)
    values (u.week_id, 'actual_abs0000', u.original_filename, u.storage_path, u.status, u.row_count, u.skipped_count, u.error_report)
    returning id into new_id;

    update actual_rows set upload_file_id = new_id
    where week_id = u.week_id and upload_file_id is null;
  end loop;
end $$;

delete from uploads where file_type = 'actual_abs0000';

-- 2) ±1-day matching. Actual transfers whose own date has no plan, but whose
-- route + product group is planned one day earlier/later, are suggested and
-- only credited once a user confirms. One current decision per actual group
-- (its own transfer date + route + group); process-week reads these on every
-- run so a decision survives re-uploads and reprocessing.
create table tracking_date_shift_decisions (
  id uuid primary key default gen_random_uuid(),
  week_id uuid not null references weeks (id) on delete cascade,
  transfer_date date not null,
  origin_code text not null,
  origin_name text not null,
  dest_code text not null,
  dest_name text not null,
  product_group text not null,
  target_plan_date date not null,
  weight_kg numeric not null,
  decision text not null check (decision in ('confirmed', 'rejected')),
  decided_by uuid,
  decided_by_name text,
  created_at timestamptz not null default now(),
  unique (week_id, transfer_date, origin_code, dest_code, product_group)
);

alter table tracking_date_shift_decisions enable row level security;

create policy tracking_date_shift_decisions_all on tracking_date_shift_decisions
  for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on tracking_date_shift_decisions to anon, authenticated;

-- System-generated remark per tracking row (regenerated by process-week),
-- kept apart from the user-editable `remark`.
alter table tracking_results add column system_note text;

alter table unmatched_actual
  add column suggested_plan_date date,
  add column day_offset int,
  add column shift_status text check (shift_status in ('pending', 'rejected'));
